name: PR Branch Check

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from develop branch
        if: github.base_ref == 'main' && github.head_ref != 'develop'
        run: exit 1
